<#
.SYNOPSIS
    Syncs local .github/skills/* folders with the upstream github/awesome-copilot repository.

.DESCRIPTION
    Fetches SKILL.md and any references/ content from the upstream skills directory and
    writes them to the corresponding local folder. Records the source commit SHA and sync
    timestamp in each skill's SOURCE.md file so drift can be detected over time.

    The set of skills to sync is discovered from the existing folders under .github/skills/.
    New skills are never added by this script — curate the list by creating the folder first
    (empty is fine) and then running sync.

.PARAMETER SkillName
    Optional. Sync only the named skill instead of all local skills.

.PARAMETER Check
    Do not write any files. Exit with a non-zero code if any local skill differs from upstream
    or if any SOURCE.md is missing / stale. Intended for CI use.

.PARAMETER Force
    Overwrite local files even when SOURCE.md indicates the local copy is already at the
    upstream SHA.

.EXAMPLE
    pwsh ./scripts/sync-skills.ps1
    Sync all skills.

.EXAMPLE
    pwsh ./scripts/sync-skills.ps1 -SkillName codeql
    Sync only the codeql skill.

.EXAMPLE
    pwsh ./scripts/sync-skills.ps1 -Check
    Report drift without writing files. CI-friendly.

.NOTES
    Upstream:   https://github.com/github/awesome-copilot
    Base path:  skills/<name>/
    Raw URL:    https://raw.githubusercontent.com/github/awesome-copilot/main/skills/<name>/<file>
    API URL:    https://api.github.com/repos/github/awesome-copilot/contents/skills/<name>
#>

[CmdletBinding()]
param(
    [string] $SkillName,
    [switch] $Check,
    [switch] $Force
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$script:UpstreamOwner = 'github'
$script:UpstreamRepo  = 'awesome-copilot'
$script:UpstreamRef   = 'main'
$script:UpstreamBase  = 'skills'

$repoRoot     = Split-Path -Parent $PSScriptRoot
$skillsRoot   = Join-Path $repoRoot '.github/skills'
$apiRootUrl   = "https://api.github.com/repos/$script:UpstreamOwner/$script:UpstreamRepo"
$rawRootUrl   = "https://raw.githubusercontent.com/$script:UpstreamOwner/$script:UpstreamRepo/$script:UpstreamRef"

$headers = @{
    'User-Agent' = 'sync-skills.ps1'
    'Accept'     = 'application/vnd.github+json'
}
if ($env:GITHUB_TOKEN) {
    $headers['Authorization'] = "Bearer $env:GITHUB_TOKEN"
}

function Get-UpstreamCommitSha {
    [CmdletBinding()]
    param([Parameter(Mandatory)][string] $Path)

    $uri = "$apiRootUrl/commits?path=$Path&sha=$script:UpstreamRef&per_page=1"
    $commits = Invoke-RestMethod -Uri $uri -Headers $headers -Method Get
    if (-not $commits -or $commits.Count -eq 0) {
        throw "No upstream commit found for path '$Path'."
    }
    return $commits[0].sha
}

function Get-UpstreamTree {
    [CmdletBinding()]
    param([Parameter(Mandatory)][string] $SkillPath)

    $uri = "$apiRootUrl/contents/$SkillPath`?ref=$script:UpstreamRef"
    try {
        $entries = Invoke-RestMethod -Uri $uri -Headers $headers -Method Get
    }
    catch {
        throw "Failed to list upstream contents for '$SkillPath': $($_.Exception.Message)"
    }

    $files = [System.Collections.Generic.List[object]]::new()
    foreach ($entry in $entries) {
        if ($entry.type -eq 'file') {
            $files.Add([pscustomobject]@{ Path = $entry.path; Name = $entry.name })
        }
        elseif ($entry.type -eq 'dir') {
            $children = Get-UpstreamTree -SkillPath $entry.path
            foreach ($child in $children) { $files.Add($child) }
        }
    }
    return $files
}

function Get-RawContent {
    [CmdletBinding()]
    param([Parameter(Mandatory)][string] $Path)

    $uri = "$rawRootUrl/$Path"
    return Invoke-WebRequest -Uri $uri -Headers $headers -Method Get -UseBasicParsing |
        Select-Object -ExpandProperty Content
}

function Read-LocalSourceMetadata {
    [CmdletBinding()]
    param([Parameter(Mandatory)][string] $SourcePath)

    if (-not (Test-Path -LiteralPath $SourcePath)) { return $null }

    $meta = [ordered]@{}
    foreach ($line in Get-Content -LiteralPath $SourcePath) {
        if ($line -match '^\s*([A-Za-z_][A-Za-z0-9_]*)\s*:\s*(.+?)\s*$') {
            $meta[$Matches[1]] = $Matches[2]
        }
    }
    return $meta
}

function Write-SourceMetadata {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][string] $SourcePath,
        [Parameter(Mandatory)][string] $SkillName,
        [Parameter(Mandatory)][string] $Sha
    )

    $content = @"
# Skill Source Metadata
# Auto-generated by scripts/sync-skills.ps1 — do not edit manually.

upstream_repo: $script:UpstreamOwner/$script:UpstreamRepo
upstream_ref:  $script:UpstreamRef
upstream_path: $script:UpstreamBase/$SkillName
upstream_sha:  $Sha
synced_at:     $([DateTimeOffset]::UtcNow.ToString('o'))
synced_by:     sync-skills.ps1
"@
    Set-Content -LiteralPath $SourcePath -Value $content -Encoding utf8
}

function Sync-Skill {
    [CmdletBinding()]
    param([Parameter(Mandatory)][string] $Name)

    $skillPath  = "$script:UpstreamBase/$Name"
    $localDir   = Join-Path $skillsRoot $Name
    $sourceFile = Join-Path $localDir 'SOURCE.md'

    if (-not (Test-Path -LiteralPath $localDir)) {
        Write-Warning "Local folder missing for skill '$Name' — skipping."
        return [pscustomobject]@{ Name = $Name; Status = 'missing-local'; Drift = $true }
    }

    $upstreamSha = Get-UpstreamCommitSha -Path $skillPath
    $localMeta   = Read-LocalSourceMetadata -SourcePath $sourceFile
    $localSha    = if ($localMeta -and $localMeta.Contains('upstream_sha')) { $localMeta['upstream_sha'] } else { $null }

    $inSync = ($localSha -eq $upstreamSha) -and (Test-Path -LiteralPath $sourceFile)
    if ($inSync -and -not $Force) {
        Write-Host "[=] $Name  (up to date @ $($upstreamSha.Substring(0,7)))"
        return [pscustomobject]@{ Name = $Name; Status = 'up-to-date'; Drift = $false }
    }

    if ($Check) {
        Write-Host "[!] $Name  (drift: local=$localSha upstream=$($upstreamSha.Substring(0,7)))" -ForegroundColor Yellow
        return [pscustomobject]@{ Name = $Name; Status = 'drift'; Drift = $true }
    }

    Write-Host "[>] $Name  (syncing to $($upstreamSha.Substring(0,7)))" -ForegroundColor Cyan

    $files = Get-UpstreamTree -SkillPath $skillPath
    foreach ($file in $files) {
        $relative = $file.Path.Substring($skillPath.Length).TrimStart('/')
        if ($relative -eq 'SOURCE.md') { continue }
        $targetPath = Join-Path $localDir $relative
        $targetDir  = Split-Path -Parent $targetPath
        if (-not (Test-Path -LiteralPath $targetDir)) {
            New-Item -ItemType Directory -Path $targetDir -Force | Out-Null
        }
        $content = Get-RawContent -Path $file.Path
        Set-Content -LiteralPath $targetPath -Value $content -Encoding utf8
    }

    Write-SourceMetadata -SourcePath $sourceFile -SkillName $Name -Sha $upstreamSha
    return [pscustomobject]@{ Name = $Name; Status = 'synced'; Drift = $false }
}

$targets = if ($SkillName) {
    , $SkillName
}
else {
    Get-ChildItem -LiteralPath $skillsRoot -Directory | Sort-Object Name | Select-Object -ExpandProperty Name
}

$results = foreach ($name in $targets) {
    try {
        Sync-Skill -Name $name
    }
    catch {
        Write-Error "[x] $name  $($_.Exception.Message)"
        [pscustomobject]@{ Name = $name; Status = 'error'; Drift = $true }
    }
}

Write-Host ''
Write-Host 'Summary:'
$results | Format-Table -AutoSize | Out-String | Write-Host

if ($Check -and ($results | Where-Object { $_.Drift })) {
    exit 1
}